name: sustag-widget
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - geopandas
  - shapely
  - pyarrow
  - plotly
  - pip
  - pip:
    - dash
    - dash-leaflet>=1.0
